//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COURRIEREntities8 : DbContext
    {
        public COURRIEREntities8()
            : base("name=COURRIEREntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<LICENCIAS> LICENCIAS { get; set; }
        public virtual DbSet<NOMINA> NOMINA { get; set; }
        public virtual DbSet<RECEPCION> RECEPCION { get; set; }
        public virtual DbSet<SALIDAEMPLEADOS> SALIDAEMPLEADOS { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }
        public virtual DbSet<VACACIONES> VACACIONES { get; set; }
    }
}
