//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALIDAEMPLEADOS
    {
        public int ID { get; set; }
        public Nullable<int> EMPLEADO { get; set; }
        public string MOTIVO { get; set; }
        public string TIPO_SALIDA { get; set; }
        public string FECHA_SALIDA { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
